version: 2

sources:
  - name: raw
    description: "Raw data sources loaded from MongoDB via Airflow EL process"
    database: analytics_db
    schema: public
    tables:
      - name: transactions_raw
        description: "RAW transaction data extracted from MongoDB. JSON fields parsed in STG layer."
        columns:
          - name: mongo_id
            description: "MongoDB document ID"
            tests:
              - unique
              - not_null
          - name: transaction_id
            description: "Unique transaction identifier"
          - name: user_id
            description: "User identifier"
          - name: amount
            description: "Transaction amount"
          - name: currency
            description: "Transaction currency (USD, EUR, RUB)"
          - name: transaction_type
            description: "Type of transaction (debit, credit, transfer, etc.)"
          - name: merchant_category
            description: "Category of merchant"
          - name: merchant_name
            description: "Name of merchant"
          - name: is_fraud
            description: "Fraud flag"
          - name: risk_score
            description: "Risk score (0-1)"
          - name: timestamp
            description: "Transaction timestamp"
            tests:
              - not_null
          # JSON поля для парсинга в DBT
          - name: location_json
            description: "Location data as JSONB (country, city, lat, lon)"
          - name: device_info_json
            description: "Device info as JSONB (device_type, os, ip_address)"
          - name: metadata_json
            description: "Metadata as JSONB (session_id, etc.)"
